### PR TITLE
adding IANA values

### LINKED ISSUE #66: IANA Considerations Update
A couple of tweaks are needed for the IANA Considerations Section:

- Based on input from the IANA TLS DEs, it seems like we need a column added to the TLS ExtensionType Values registry to indicate that an extension is DTLS-only.
- The column values for TLS 1.3 and Recommended are missing.  Suggest blank for TLS 1.3 and N for Recommended.
- Add a note to say that connection_id is DTLS1.2 only.
- Add instructions for IANA to assign "Y" to DTLS-okay column for tls12_cid content type.

### PR DESCRIPTION
**Pull request by seanturner**
We need to tell IANA what to assign to all of the columns.

Closes #66

### CODE REVIEW

**Comment by jsalowey** [comment]
Looks good

**Comment by richsalz** [comment]
ship it

**Comment by boaks** [comment]
Sorry, I wanted to add this to the issue #66 , not the PR.

++++++++++++++++++++

That results in 

"DTLS only" for TLS extensions and
"DTLS-OK" for TLS parameters.

I'm not sure, if that just represents more the "current" usage than the "logic" behind it. 
I would be afraid, that this will hold up other ideas, which doesn't match that "only for extensions / ok for parameters" pattern.

**Comment by seanturner** [comment]
See:
https://mailarchive.ietf.org/arch/msg/tls/JdKKK2kKumrt4Z-51Fqx-JI9QsU

**Comment by hannestschofenig** [comment]
This PR has been replaced by text offered in https://github.com/tlswg/dtls-conn-id/pull/68

**Pull request closed without merging**
